INSERT INTO `mydb`.`habitaciones` (`NUMERO`, `CAPACIDAD`, `ESTADO`) VALUES
(1, 2, 'DESOCUPADA'),
(2, 2, 'OCUPADA'),
(3, 3, 'DESOCUPADA'),
(4, 3, 'FUERA_DE_SERVICIO'),
(5, 4, 'DESOCUPADA'),
(6, 4, 'OCUPADA'),
(7, 5, 'DESOCUPADA'),
(8, 5, 'OCUPADA'),
(9, 6, 'DESOCUPADA'),
(10, 6, 'FUERA_DE_SERVICIO');


INSERT INTO `empleado` (`idEMPLEADO`, `NOMBRE_COMPLETO`, `USUARIO`, `PASSWORD`, `ROL`)
VALUES (NULL, 'ADMIN', 'ADMIN', 'ADMIN123', 'ADMIN');


